name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        id: build
        run: ./gradlew build
        continue-on-error: true

      - name: Run tests
        id: test
        run: |
          ./gradlew test
          TEST_RESULT=$?
          echo "TEST_EXIT_CODE=$TEST_RESULT" >> $GITHUB_ENV
          if [ $TEST_RESULT -ne 0 ]; then
            echo "Some tests failed."
            exit 0 # exit 0 to continue workflow but note the failure
          fi
        continue-on-error: true

      - name: Generate coverage report
        if: always()
        run: ./gradlew jacocoTestReport

      - name: Install xunit-viewer
        run: npm install -g xunit-viewer

      - name: Convert JUnit XML to HTML
        run: xunit-viewer --results=build/test-results/test --output=build/reports/tests/test/index.html

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Check build and test results
        if: always()
        run: |
          BUILD_EXIT_CODE=$(cat $GITHUB_ENV | grep BUILD_EXIT_CODE | cut -d '=' -f 2)
          TEST_EXIT_CODE=$(cat $GITHUB_ENV | grep TEST_EXIT_CODE | cut -d '=' -f 2)
          if [ "$BUILD_EXIT_CODE" -ne 0 ] || [ "$TEST_EXIT_CODE" -ne 0 ]; then
            echo "Build or tests failed."
            exit 1
          fi











