name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # JDK 11 설정
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Gradle로 빌드
      - name: Build with Gradle
        run: |
          ./gradlew build
          echo "BUILD_EXIT_CODE=$?" >> $GITHUB_ENV

      # 테스트 실행 (오류 발생 시 전체 워크플로우 실패로 표시)
      - name: Run tests and capture result
        run: |
          ./gradlew test || true
          echo "TEST_EXIT_CODE=$?" >> $GITHUB_ENV

      # 커버리지 보고서 생성
      - name: Generate coverage report
        run: ./gradlew jacocoTestReport || true

      # xunit-viewer 설치
      - name: Install xunit-viewer
        run: npm install -g xunit-viewer || true

      # JUnit XML을 HTML로 변환
      - name: Convert JUnit XML to HTML
        run: |
          xunit-viewer --results=build/test-results/test --output=build/reports/tests/test/index.html
          || true

      # 커버리지 보고서 업로드
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html

      # JUnit 테스트 보고서 업로드
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      # 빌드 또는 테스트 실패 시 워크플로우 실패로 표시
      - name: Fail workflow if build or tests failed
        if: env.BUILD_EXIT_CODE != '0' || env.TEST_EXIT_CODE != '0'
        run: exit 1



