name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # JDK 11 설정
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Gradle로 빌드
      - name: Build with Gradle
        run: ./gradlew build --continue || true

      # 테스트 실행
      - name: Run tests
        run: ./gradlew test --continue || true

      # 커버리지 보고서 생성
      - name: Generate coverage report
        run: ./gradlew jacocoTestReport || true

      # 커버리지 보고서 업로드
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html

      # JUnit 테스트 보고서 업로드
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/test-results/test
