name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        id: build
        run: |
          ./gradlew build
        continue-on-error: true

      - name: Run tests
        id: test
        run: |
          ./gradlew test --continue
          echo "TEST_EXIT_CODE=$?" >> $GITHUB_ENV
        continue-on-error: true

      - name: Generate coverage report
        if: always()
        run: ./gradlew jacocoTestReport
        continue-on-error: true

      - name: Install xunit-viewer
        run: npm install -g xunit-viewer
        continue-on-error: true

      - name: Convert JUnit XML to HTML
        run: xunit-viewer --results=build/test-results/test --output=build/reports/tests/test/index.html
        continue-on-error: true

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html
        continue-on-error: true

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test
        continue-on-error: true

      - name: Check build and test results
        if: always()
        run: |
          if [ "${{ env.BUILD_EXIT_CODE }}" -ne 0 ] || [ "${{ env.TEST_EXIT_CODE }}" -ne 0 ]; then
            echo "Build or tests failed."
            exit 1
          fi










